language: scala
scala:
- 2.11.6
jdk:
- oraclejdk8
script: ./scripts/ci-build.sh
env:
  global:
  - LIB_VERSION=$TRAVIS_BUILD_NUMBER
  - secure: aRx3xcH6wsI+p4WeQOGbRkymU4O+05zHlvpJdz+r1XODH5l576U42JYCNk23ItMGvDcYPvETvINRzoI+hpp2A2+23+OGR+AbGNfr4HF5OIHh9XxEDNldk2IREfdvJ0r4pV/NMABQH45X/s+Jq0umCPR7Z9clTcuwKJ8gBUDn7i8=
notifications:
  email: false
after_success:
  - cd target
  - 'ASSETID=$(curl -s -H "Authorization: token ${GITHUBTOKEN}" "https://api.github.com/repos/alltonp/reprobate/releases/881828/assets" | jq ".[0].id")'
  - 'curl -XDELETE -s -H "Authorization: token ${GITHUBTOKEN}" "https://api.github.com/repos/alltonp/reprobate/releases/assets/$ASSETID"'
  - 'curl -XPOST -s -H "Authorization: token ${GITHUBTOKEN}" -H "Content-Type: application/zip" --data-binary @./dist.zip "https://uploads.github.com/repos/alltonp/reprobate/releases/881828/assets?name=reprobate.zip"'

wip:
- ./scripts/create-release.sh
